"""
Reads a generated payroll Excel, matches employees to their emails,
and sends each stub as an HTML email.
"""
from __future__ import annotations

import re
import smtplib
import unicodedata
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Callable

import yaml
from openpyxl import load_workbook
from rapidfuzz import process as fz_process

import payroll.template_loader as tl
from payroll.config import CELL_MAP, BLOCK_TOP_LEFT, BLOCK_BOTTOM_RIGHT, GAP_ROWS, DATA_SHEET
from payroll.services.send_logger import write_log
from payroll.utils.a1rc import a1_to_rc

# ── constants derived from config ─────────────────────────────────────────────
_r1, _c1 = a1_to_rc(BLOCK_TOP_LEFT)
_r2, _c2 = a1_to_rc(BLOCK_BOTTOM_RIGHT)
_BLOCK_HEIGHT = _r2 - _r1 + 1
_STRIDE = _BLOCK_HEIGHT + GAP_ROWS

FUZZY_THRESHOLD = 88  # minimum score to accept a name match

# ── helpers ───────────────────────────────────────────────────────────────────

def get_work_shift(sector: str):
    numbers = re.findall(r'\d', sector)
    if len(numbers) == 0:
        numbers = [1]
    return numbers[-1]

def fmt_work_shift(text: str):
    pattern = r"(turno )?(T)?\d"
    match = re.search(pattern, text)
    unmatched_before = text
    if match:
        unmatched_before = text[:match.start()]
    return unmatched_before.rstrip()

def _normalize(s: str) -> str:
    s = unicodedata.normalize("NFD", s)
    s = "".join(c for c in s if unicodedata.category(c) != "Mn")
    return " ".join(s.upper().split())


def _load_smtp_config() -> dict:
    cfg_path = tl.find_config()
    with open(cfg_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if "smtp" not in data:
        raise KeyError(
            f"Falta la sección 'smtp' en {cfg_path}\n"
            "Agrega host, port, user y password bajo la clave smtp:"
        )
    return data["smtp"]


# ── payroll Excel parser ──────────────────────────────────────────────────────

def parse_payroll_excel(payroll_file: str) -> dict[str, dict]:
    """
    Returns {normalized_name: {field: value, ...}} for every stub in the file.
    Works on any Excel generated by this app regardless of sheet names.
    """
    wb = load_workbook(payroll_file, data_only=True)
    stubs: dict[str, dict] = {}

    name_rel_r, name_rel_c = a1_to_rc(CELL_MAP["name"])

    for ws in wb.worksheets:
        block_index = 0
        while True:
            base_row = _r1 + block_index * _STRIDE

            # Read name cell; stop when empty
            name_row = base_row + (name_rel_r - 1)
            name_col = name_rel_c
            raw_name = ws.cell(row=name_row, column=name_col).value
            if not raw_name:
                break

            stub: dict = {}
            for field, a1 in CELL_MAP.items():
                rel_r, rel_c = a1_to_rc(a1)
                val = ws.cell(row=base_row + rel_r - 1, column=rel_c).value
                stub[field] = val if val is not None else 0

            key = _normalize(str(stub["name"]))
            stubs[key] = stub
            block_index += 1

    return stubs


# ── email-list loader ─────────────────────────────────────────────────────────

def load_email_map(data_file: str, progress_cb: Callable) -> dict[str, str]:
    """Returns {normalized_name: email} from the correo_electronico column in the control file."""
    cfg_path = tl.find_config()
    with open(cfg_path, "r", encoding="utf-8") as f:
        datos = yaml.safe_load(f)["datos"]

    col_map: dict[str, int] = {}
    for d in datos:
        for k, v in d.items():
            col_map[k] = ord(v) - ord("A")

    name_col = col_map.get("nombre_colaborador")
    email_col = col_map.get("correo_electronico")

    if name_col is None or email_col is None:
        raise KeyError(
            "Faltan 'nombre_colaborador' o 'correo_electronico' en config.yaml bajo datos:"
        )

    wb = load_workbook(data_file, data_only=True)
    uppercase_names = [s.upper() for s in wb.sheetnames]
    if DATA_SHEET not in uppercase_names:
        raise ValueError(f"Pestaña '{DATA_SHEET}' no encontrada en {data_file}")
    ws = wb[wb.sheetnames[uppercase_names.index(DATA_SHEET)]]

    result: dict[str, str] = {}
    for row in ws.iter_rows(min_row=2, values_only=True):
        name_val  = row[name_col]  if len(row) > name_col  else None
        email_val = row[email_col] if len(row) > email_col else None
        if name_val and email_val:
            email_str = str(email_val).strip()
            if not email_str.isascii():
                progress_cb(f"✗ Correo malformado (caracteres no ASCII) para '{name_val}': {email_str}")
                continue
            elif not re.match(r'^[^\s@,]+@[^\s@,]+\.[^\s@,]+$', email_str):
                progress_cb(f"✗ Correo malformado (no cumple con el patrón local@dominio.tld) para '{name_val}': {email_str}")
                continue
            else:
                result[_normalize(str(name_val))] = email_str
    return result


# ── fuzzy name matcher ────────────────────────────────────────────────────────

def _find_email(norm_name: str, email_map: dict[str, str]) -> str | None:
    if norm_name in email_map:
        return email_map[norm_name]
    match = fz_process.extractOne(norm_name, email_map.keys(), score_cutoff=FUZZY_THRESHOLD)
    if match:
        return email_map[match[0]]
    return None


# ── HTML renderer ─────────────────────────────────────────────────────────────

def _fmt(val) -> str:
    if isinstance(val, float):
        return f" ${val:,.2f}"
    return str(val) if val else "—"


def _load_logo_bytes() -> bytes | None:
    try:
        return tl.packaged_default_path("Logo.png").read_bytes()
    except (FileNotFoundError, OSError):
        return None


def render_stub_html(stub: dict, has_logo: bool = False) -> str:
    name     = stub.get("name", "")
    unit     = stub.get("unit", "")
    week     = stub.get("week", "")
    pay_date = stub.get("pay_date", "")
    base_salay = stub.get("salary", 0)

    earnings = [
        ("Total semana",        stub.get("weekly_total", 0)), # TODO
        ("Tiempo extra",       stub.get("extra_time", 0)),
        ("Bono",        stub.get("bonus", 0)),
        ("Prima vacacional",   stub.get("prime_vacation", 0)),
        ("Vacaciones",         stub.get("vacation", 0)),
        ("Préstamo",           stub.get("loan", 0)),
    ]
    deductions = [
        ("Deducción horas",    stub.get("hours_deduction", 0)),
        ("Infonavit",          stub.get("Infonavit", 0)),   
        ("Fonacot",            stub.get("Fonacot", 0)),
        ("Desc. préstamo",     stub.get("loan_discount", 0)),
        ("Permiso sin goce de sueldo",     0),
    ]

    def sum_items(items):
        return sum(float(x[1]) for x in items)

    def col_rows_html(items):
        rows = "".join(
            f'<tr>'
            f'<td style="font-size:13px;color:#666666;padding-bottom:4px">{label}</td>'
            f'<td style="font-size:13px;color:#666666;padding-bottom:4px;text-align:right;white-space:nowrap;padding-left:12px">{_fmt(float(val))}</td>'
            f'</tr>'
            for label, val in items
        )
        return f'<table style="width:100%;border-collapse:collapse">{rows}</table>'

    def col_subtotal_html(items):
        td_style = "font-size:13px;font-weight:600;color:#111111;padding-top:8px;border-top:1px solid #e0ddd8"
        return (
            f'<table style="width:100%;border-collapse:collapse;margin-top:8px"><tr>'
            f'<td style="{td_style}">Subtotal</td>'
            f'<td style="{td_style};text-align:right;white-space:nowrap;padding-left:12px">{_fmt(sum_items(items))}</td>'
            f'</tr></table>'
        )

    logo_cell = (
        '<td style="width:110px;padding:20px 0 20px 24px;vertical-align:top">'
        '<img src="cid:payroll_logo" alt="Logo" width="100" '
        'style="height:100px;width:100px;display:block;border:0;outline:none;text-decoration:none" />'
        '</td>'
        if has_logo else ""
    )
    text_cell_padding = "padding:20px 24px 20px 18px" if has_logo else "padding:20px 24px"

    total_neto = sum_items(earnings) - sum_items(deductions)

    return f"""<!DOCTYPE html>
<html lang="es">
<head><meta charset="UTF-8" /></head>
<body style="font-family:Arial,sans-serif;background:#ede9e3;margin:0;padding:48px 16px">
  <div style="width:100%;max-width:480px;margin:auto;background:#ffffff;border:0.5px solid #e0ddd8">

    <table style="width:100%;border-collapse:collapse;border-left:3px solid #B8892A">
      <tr>
        {logo_cell}
        <td style="{text_cell_padding};vertical-align:top">
          <p style="font-size:18px;font-weight:600;color:#111111;margin:0 0 2px">{name}</p>
          <p style="font-size:14px;color:#666666;font-style:italic;line-height:1.6;margin:0">
            Centro de trabajo: {fmt_work_shift(unit)}<br />
            Turno: {get_work_shift(unit)}<br />
            Semana: {week}<br />
            Fecha de pago: {pay_date}<br />
            Salario base: {_fmt(float(base_salay) / 7)}
          </p>
        </td>
      </tr>
    </table>

    <hr style="border:none;border-top:0.5px solid #E8D5A8;margin:0" />

    <table style="width:100%;border-collapse:collapse">
      <tr>
        <td style="width:50%;padding:16px 24px;vertical-align:top">
          <p style="font-size:9px;letter-spacing:0.18em;color:#B8892A;text-transform:uppercase;margin:0 0 10px">Percepciones</p>
          {col_rows_html(earnings)}
          {col_subtotal_html(earnings)}
        </td>
        <td style="width:1px;background:#E8D5A8"></td>
        <td style="padding:16px 24px;vertical-align:top">
          <p style="font-size:9px;letter-spacing:0.18em;color:#B8892A;text-transform:uppercase;margin:0 0 10px">Deducciones</p>
          {col_rows_html(deductions)}
          {col_subtotal_html(deductions)}
        </td>
      </tr>
    </table>

    <div style="padding:14px 24px;display:flex;justify-content:space-between;align-items:baseline;border-top:0.5px solid #E8D5A8">
      <span style="font-size:11px;letter-spacing:0.14em;text-transform:uppercase;color:#666666">Total neto</span>
      <span style="font-size:18px;font-weight:600;color:#B8892A">{_fmt(total_neto)}</span>
    </div>

    <div style="padding:10px 24px;background:#f7f5f2;border-top:0.5px solid #e0ddd8;text-align:center;font-size:11px;font-style:italic;color:#666666">
      Este recibo fue generado automáticamente.
    </div>

  </div>
</body>
</html>"""


# ── main entry point ──────────────────────────────────────────────────────────

def send_payroll_emails(
    payroll_file: str,
    data_file: str,
    progress_cb: Callable[[str], None] = print,
) -> None:
    smtp_cfg = _load_smtp_config()
    host     = smtp_cfg.get("host", "")
    port     = int(smtp_cfg.get("port", 587))
    user     = smtp_cfg.get("user", "")
    password = smtp_cfg.get("password", "")
    from_name = smtp_cfg.get("from_name", "PAYROLL")

    if not host or not user or not password:
        cfg_path = tl.find_config()
        raise ValueError(
            f"Credenciales SMTP incompletas en {cfg_path}\n"
            "Completa host, user y password bajo smtp:"
        )

    progress_cb("Leyendo archivo de recibos…")
    stubs = parse_payroll_excel(payroll_file)
    progress_cb(f"{len(stubs)} recibos encontrados.")

    progress_cb("Leyendo correos del archivo de control…")
    email_map = load_email_map(data_file, progress_cb)
    progress_cb(f"\n{len(email_map)} correos cargados.")

    logo_bytes = _load_logo_bytes()
    sent = skipped = 0
    log_results: list[dict] = []

    progress_cb("Conectando al servidor SMTP…")
    with smtplib.SMTP(host, port, timeout=15) as server:
        server.ehlo()
        server.starttls()
        server.login(user, password)
        progress_cb("Sesión SMTP iniciada.")

        for norm_name, stub in stubs.items():
            recipient = _find_email(norm_name, email_map)
            display_name = stub.get("name", norm_name)

            if not recipient:
                progress_cb(f"  - Sin correo para: {display_name}")
                log_results.append({"email": "", "name": display_name, "sent": False})
                skipped += 1
                continue

            html_part = MIMEText(render_stub_html(stub, has_logo=bool(logo_bytes)), "html", "utf-8")

            msg = MIMEMultipart("related")
            msg["Subject"] = f"Recibo de nómina — {stub.get('week', '')}"
            msg["From"]    = f"{from_name} <{user}>"
            msg["To"]      = recipient
            msg.attach(html_part)

            if logo_bytes:
                logo_img = MIMEImage(logo_bytes, "png")
                logo_img.add_header("Content-ID", "<payroll_logo>")
                logo_img.add_header("Content-Disposition", "inline", filename="Logo.png")
                msg.attach(logo_img)

            server.sendmail(user, recipient, msg.as_string())
            progress_cb(f"  > Enviado a {display_name} <{recipient}>")
            log_results.append({"email": recipient, "name": display_name, "sent": True})
            sent += 1

    log_path = write_log(log_results)
    progress_cb(f"\nListo. {sent} enviados, {skipped} sin correo.")
    progress_cb(f"Log guardado en {log_path}")
